package com.astro.entity.InventoryModule;

import lombok.Data;

import javax.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

@Entity
@Data
@Table(name = "goods_receipt_inspection")
@EntityListeners(AuditingEntityListener.class)
public class GoodsReceiptInspection {

  //  @Id
 //   @Column(name = "gri_id")
  //  private String griId;

    @Id
    @Column(name = "gri_id")
    private String griId;

    @Column(name = "installation_date")
    private LocalDate installationDate;

    @Column(name = "commissioning_date")
    private LocalDate commissioningDate;

    @Column(name = "asset_code")
    private String assetCode;

    @Column(name = "additional_material_description")
    private String additionalMaterialDescription;

    @Column(name = "locator")
    private String locator;

    @Column(name = "print_label_option", columnDefinition = "BOOLEAN DEFAULT false")
    private boolean printLabelOption;

    @Column(name = "depreciation_rate")
    private double depreciationRate;


    private double bookValue;  //autogenerated value

    @Column(name = "attach_component_popup")
    private String attachComponentPopup;

    @LastModifiedBy
    private String updatedBy;

    @CreatedBy
    private String createdBy;

    @CreatedDate
    private LocalDateTime createdDate;

    @LastModifiedDate
    private LocalDateTime updatedDate;





}
